import { chromium } from '@playwright/test';
import fs from 'node:fs';
const browser = await chromium.launch({channel: 'chrome', headless: true});
const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://127.0.0.1:18880/wp-login.php');
await page.locator('#user_login').fill('ri_admin');
await page.locator('#user_pass').fill('ri-local-test-password');
await Promise.all([page.waitForURL('**/wp-admin/**'), page.locator('#wp-submit').click()]);
await page.goto('http://127.0.0.1:18880/wp-admin/admin.php?page=request-inspector');
await page.locator('#request-inspector-app h1').waitFor();
await page.waitForTimeout(1500);
fs.mkdirSync('test-results', {recursive: true});
await page.screenshot({path: 'test-results/explorer.png', fullPage: true});
console.log((await page.locator('#request-inspector-app').innerText()).slice(0, 3500));
await page.goto('http://127.0.0.1:18880/wp-admin/admin.php?page=request-inspector-settings');
await page.locator('#request-inspector-app h1').waitFor();
await page.waitForTimeout(1000);
await page.screenshot({path: 'test-results/settings.png', fullPage: true});
await browser.close();
if (errors.length) throw new Error(errors.join('\n'));
console.log('PASS: native WordPress login, Explorer and Settings render without browser errors.');
